# Generated by Django 3.2.23 on 2023-12-03 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('author', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'question')},
        ),
    ]
