# Generated by Django 3.2.23 on 2023-12-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20231203_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
